# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 571, 381))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.heigh = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.heigh.setMinimum(0.01)
        self.heigh.setMaximum(2.5)
        self.heigh.setSingleStep(0.01)
        self.heigh.setObjectName("heigh")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.heigh)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.weight = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.weight.setObjectName("weight")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.weight)
        self.claculate = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.claculate.setObjectName("claculate")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.claculate)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.result = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.result.setObjectName("result")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.result)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "K&ouml;rper Gr&ouml;ße in m:"))
        self.label_2.setText(_translate("MainWindow", "Gewicht im kg: "))
        self.claculate.setText(_translate("MainWindow", "IBM brechnen"))
        self.label_3.setText(_translate("MainWindow", "Dein BMI:"))
        self.result.setText(_translate("MainWindow", "20"))
